In [1]:
from google.colab import drive
drive.mount("/content/gdrive")
!ls "/content/gdrive/MyDrive/data"

Mounted at /content/gdrive
 face.csv	        feature_extractByPretrain.npy
 faceData	        model4emotionClassfier
 faceData2D	        model4multiClassfier
 faceData2DWithNumber  'model4multiClassfier(exceptAge)'
 face_Dataset	        model4raceClassfier
 faceDataset	        model4sexClassfier
 faceDataset2	        model4sexClassfierWithoutValid
 faceDataWithNumber     rawdata
 faceDR		        rawdata.zip
 faceDS		        vgg_face_dag.pth
 faceLabel.csv

In [2]:
import matplotlib.pyplot as plt  # show image
import numpy as np
import pandas as pd
import sys
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
dtype = np.uint8
shape = (128,128)

# file_path /content/gdrive/My Drive/data/rawdata/xxxx
pre_img_path="/content/gdrive/MyDrive/data/rawdata/"
pre_path="/content/gdrive/MyDrive/data/"

# Read the data from the binary file
# data = np.fromfile(file_path, dtype=dtype).reshape(shape)

In [4]:
face=pd.read_csv(pre_path+"faceLabel.csv")

In [5]:
face.head()

,number,sex,age,race,emotion,extra,sex_label,age_adult,age_child,age_senior,...,race_black,race_hispanic,race_other,race_white,emotion_funny,emotion_serious,emotion_smiling,race_label,emotion_label,age_label
0,1223,male,child,white,smiling,NaN,1,0,1,0,...,0,0,0,1,0,0,1,4,2,1
1,1224,male,child,white,serious,NaN,1,0,1,0,...,0,0,0,1,0,1,0,4,1,1
2,1225,male,child,white,smiling,NaN,1,0,1,0,...,0,0,0,1,0,0,1,4,2,1
3,1226,male,child,white,smiling,NaN,1,0,1,0,...,0,0,0,1,0,0,1,4,2,1
4,1227,male,child,white,serious,NaN,1,0,1,0,...,0,0,0,1,0,1,0,4,1,1

In [6]:
# face.age.unique()
face.age.describe()

count      3993
unique        4
top       adult
freq       3168
Name: age, dtype: object

In [7]:
#@title {run: "auto"}
col='emotion' # @param ["sex","age","race","emotion"]
face[col].value_counts()

serious    2014
smiling    1879
funny       100
Name: emotion, dtype: int64

In [8]:
n=int(len(face)*0.15)
face_tail=face.tail(n)

In [17]:
# @title {run: "auto"}
nn=0.2  #@param {type:"slider", min:0, max:1, step:0.01}
n=int(len(face)*nn)
face_tail=face.tail(n)
col='emotion' # @param ["sex","age","race","emotion"]
counts_post = face_tail[col+"_label"].value_counts()
proportions_post = counts_post / len(face_tail)
counts_pre = face_head[col+"_label"].value_counts()
proportions_pre = counts_pre / len(face_head)
print("前"+str((1-nn)*100)+"%,的分布如下")
print(counts_pre)
print(proportions_pre)
print("后"+str(nn*100)+"%,的分布如下")
print(counts_post)
print(proportions_post)

前80.0%,的分布如下
1    1621
2    1487
0      86
Name: emotion_label, dtype: int64
1    0.507514
2    0.465560
0    0.026925
Name: emotion_label, dtype: float64
后20.0%,的分布如下
2    392
1    392
0     14
Name: emotion_label, dtype: int64
2    0.491228
1    0.491228
0    0.017544
Name: emotion_label, dtype: float64

In [18]:
face_tail.head()

,number,sex,age,race,emotion,extra,sex_label,age_adult,age_child,age_senior,...,race_black,race_hispanic,race_other,race_white,emotion_funny,emotion_serious,emotion_smiling,race_label,emotion_label,age_label
3195,4424,female,adult,black,smiling,bandana,0,1,0,0,...,1,0,0,0,0,0,1,1,2,0
3196,4425,female,adult,black,serious,bandana,0,1,0,0,...,1,0,0,0,0,1,0,1,1,0
3197,4426,female,adult,black,smiling,bandana,0,1,0,0,...,1,0,0,0,0,0,1,1,2,0
3198,4427,female,adult,black,smiling,NaN,0,1,0,0,...,1,0,0,0,0,0,1,1,2,0
3199,4428,female,adult,black,smiling,NaN,0,1,0,0,...,1,0,0,0,0,0,1,1,2,0