In [1]:
from google.colab import drive
drive.mount("/content/gdrive")
!ls "/content/gdrive/My Drive/data"

Mounted at /content/gdrive
face.csv	      faceDataset	  faceLabel.csv
faceData	      faceDataset2	  model4sexClassfier
faceData2D	      faceDataWithNumber  model4sexClassfierWithoutValid
faceData2DWithNumber  faceDR		  rawdata
face_Dataset	      faceDS		  vgg_face_dag.pth

In [2]:
import matplotlib.pyplot as plt  # show image
import numpy as np
import pandas as pd
import sys
import tensorflow as tf

In [3]:
dtype = np.uint8
shape = (128,128)

# file_path /content/gdrive/My Drive/data/rawdata/xxxx
pre_img_path="/content/gdrive/My Drive/data/rawdata/"
pre_path="/content/gdrive/My Drive/data/"

In [18]:
face=pd.read_csv(pre_path+"faceLabel.csv")

In [19]:
face.head()

,number,sex,age,race,emotion,extra,sex_label,age_adult,age_child,age_senior,age_teen,race_asian,race_black,race_hispanic,race_other,race_white,emotion_funny,emotion_serious,emotion_smiling
0,1223,male,child,white,smiling,NaN,1,0,1,0,0,0,0,0,0,1,0,0,1
1,1224,male,child,white,serious,NaN,1,0,1,0,0,0,0,0,0,1,0,1,0
2,1225,male,child,white,smiling,NaN,1,0,1,0,0,0,0,0,0,1,0,0,1
3,1226,male,child,white,smiling,NaN,1,0,1,0,0,0,0,0,0,1,0,0,1
4,1227,male,child,white,serious,NaN,1,0,1,0,0,0,0,0,0,1,0,1,0

In [15]:
face=face.join(pd.get_dummies(face[["age","race","emotion"]],prefix=['age','race','emotion']))

In [16]:
face.head()

,number,sex,age,race,emotion,extra,sex_label,age_adult,age_child,age_senior,age_teen,race_asian,race_black,race_hispanic,race_other,race_white,emotion_funny,emotion_serious,emotion_smiling
0,1223,male,child,white,smiling,NaN,1,0,1,0,0,0,0,0,0,1,0,0,1
1,1224,male,child,white,serious,NaN,1,0,1,0,0,0,0,0,0,1,0,1,0
2,1225,male,child,white,smiling,NaN,1,0,1,0,0,0,0,0,0,1,0,0,1
3,1226,male,child,white,smiling,NaN,1,0,1,0,0,0,0,0,0,1,0,0,1
4,1227,male,child,white,serious,NaN,1,0,1,0,0,0,0,0,0,1,0,1,0

In [17]:
face.to_csv(pre_path+"faceLabel.csv",index=False)